services:
  db_postgres_github-ci-cd:
    image: postgres
    container_name: db_postgres_github-ci-cd
    restart: always
    ports:
      - 1234:5432
    env_file:
      - .env.test

  node_app_github-ci-cd:
    container_name: node_app_github-ci-cd
    build: .
    ports:
      - 5000:5000
    depends_on:
      - db_postgres_github-ci-cd
    env_file:
      - .env.test