name: PullRequest
on: [pull_request]
jobs:
  PullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_POSTGRES_USER: "postgres"
          envkey_POSTGRES_PASSWORD: "123"
          envkey_POSTGRES_DB: "banco"
          envkey_DATABASE_URL: "postgres://postgres:123@db_postgres_github-ci-cd:5432/github-ci-cd_tests"
          file_name: .env.test
      - name: Run tests
        run: docker-compose -f docker-compose-tests.yml run node_app_github-ci-cd npm run test
      - name: Build
        run: npm i && npm run build